# Generated by Django 2.1.4 on 2019-03-31 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=256)),
                ('middlename', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=30, null=True)),
                ('has_appointment', models.BooleanField(default=False)),
                ('is_waiting', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_label', models.CharField(blank=True, max_length=256, null=True)),
                ('visit_type', models.CharField(choices=[('1', 'Progress'), ('2', 'Procedure'), ('3', 'Admin')], default=1, max_length=256)),
                ('visit_notes', models.TextField(blank=True, max_length=50000)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('fk_visit_main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicalviewer.Main', verbose_name='Patient Name')),
            ],
        ),
    ]
