# Generated by Django 2.0.4 on 2019-08-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_date', models.DateField()),
                ('encounter_label', models.CharField(blank=True, max_length=256, null=True)),
                ('encounter_type', models.CharField(choices=[('1', 'Progress'), ('2', 'Procedure'), ('3', 'Admin')], default=1, max_length=256)),
                ('encounter_notes', models.TextField(blank=True, max_length=50000)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasthx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasthx_date_diagnosis', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('pasthx_notes', models.TextField(blank=True, max_length=50000)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
