# Generated by Django 2.0.4 on 2019-08-04 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasthx',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pasthx_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pasthx',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasthx_patid', to=settings.AUTH_USER_MODEL, verbose_name='Patient Name'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encuonter_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Patient Name'),
        ),
    ]
