# Generated by Django 2.0.4 on 2019-05-21 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalviewer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='fk_visit_profile',
        ),
        migrations.AddField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Patient Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
