# Generated by Django 2.2.4 on 2019-08-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalviewer', '0002_auto_20190804_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('valueset_id', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
