# Generated by Django 2.2.4 on 2019-08-04 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalviewer', '0003_encounterreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounter_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_reason', to='clinicalviewer.EncounterReason', verbose_name='Encounter Reason'),
            preserve_default=False,
        ),
    ]
