# Generated by Django 2.2 on 2019-06-20 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinicalviewer', '0003_auto_20190620_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_patid', to=settings.AUTH_USER_MODEL, verbose_name='Patient Name'),
        ),
        migrations.CreateModel(
            name='Pasthx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasthx_date_diagnosis', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField()),
                ('pasthx_notes', models.TextField(blank=True, max_length=50000)),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pasthx_created_by', to=settings.AUTH_USER_MODEL)),
                ('patid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasthx_patid', to=settings.AUTH_USER_MODEL, verbose_name='Patient Name')),
            ],
        ),
    ]
