# Generated by Django 2.2.4 on 2019-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalviewer', '0004_auto_20190804_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='free_text_label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
