# Generated by Django 2.0.4 on 2019-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190521_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='middle_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>DD-MM-YYYY</em>.', null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='medicare2',
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
