# Generated by Django 2.0.4 on 2019-05-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190522_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='medicare2',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
