# Generated by Django 2.0.4 on 2019-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190522_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='medicare1',
            field=models.IntegerField(null=True),
        ),
    ]
