# Generated by Django 2.0.4 on 2019-05-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190522_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='medicare2',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
