# Generated by Django 2.0.4 on 2019-05-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190522_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='middle_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Male'), ('2', 'Female')], max_length=20, null=True),
        ),
    ]
