# Generated by Django 2.0.2 on 2018-03-01 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date_of_birth', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.CharField(max_length=256)),
                ('visit_type', models.CharField(max_length=256)),
                ('visit_specialty', models.CharField(max_length=256)),
                ('visit_notes', models.CharField(max_length=10000)),
                ('fk_visit_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acrrmlogbook.Main')),
            ],
        ),
    ]
