# Generated by Django 2.0.2 on 2018-03-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrrmlogbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
