# Generated by Django 2.0.2 on 2018-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acrrmlogbook', '0002_visit_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_diagnosis',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_notes',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_specialty',
            field=models.CharField(choices=[('1', 'Internal Medicine'), ('2', 'Surgery'), ('3', 'Obstetrics & Gynaecology'), ('4', 'Anesthetics'), ('5', 'Paediatrics'), ('6', 'Mental Health'), ('7', 'Opthalmology'), ('8', 'Orthopedics'), ('9', 'Trauma')], default=1, max_length=256),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('1', 'Consultation'), ('2', 'Procedure')], default=1, max_length=256),
        ),
    ]
