# Generated by Django 2.0.2 on 2018-03-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acrrmlogbook', '0003_auto_20180302_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_diagnosis',
            new_name='visit_label',
        ),
    ]
